### ISSUE TITLE
Incorrect highlighting of multiline strings

### ISSUE THREAD

**Issue by pchaigno** [textmate/objective-c.tmbundle#7]
This issue was originatively reported by @meatcoder at github/linguist#2028:
> The following snippet is highlighted such that the % in the second segment of the NSString constant is shown as a syntax error. Note that this is valid Objective-C code.
```objective-c
id a = @"hello there"
          "bye %@";
```
Adding a @ to the second segment produces the correct highlighting:
```objective-c
id a = @"hello there"
          @"bye %@";
```
This % in both snippets should be highlighted in the same way.

**Comment by joachimm** [comment]
This is difficult to solve with the line by line approach that TextMate's parser uses for performance reasons.
Basically the parser does not remember the objc string when it parses the later string part. It assumes it's a c-string which does not support %@.

**Comment by pchaigno** [comment]
Thanks @sorbits!
