### ISSUE TITLE
The Documentation for Word command doesn't work

### ISSUE THREAD

**Issue by jacob-carlborg** [textmate/objective-c.tmbundle#8]
When I run the "Documentation for Word" command on any symbol I always get back "Cannot find documentation for: ...". I did some debugging and found that the problem seems to be the `Ref#exists?` method [1] in the support file "docset_query.rb". The problem is that the directory "/Applications/Xcode.app/Contents/Developer/Documentation/DocSets/com.apple.adc.documentation.OSX.docset/Contents/Resources/Documents" is empty. Although there is another directory called "Tokens" containing directories for each language and directories for each type of symbol, "clm", "instm" and so on.

I'm using OS X 10.10.1 and Xcode Version 6.2 (6C131e).

[1] https://github.com/textmate/objective-c.tmbundle/blob/master/Support/lib/docset_query.rb#L44-L46

**Comment by sorbits** [comment]
The documentation has moved around a lot, and I haven’t tested it on 
10.10, but if you go to Xcode → Preferences → Downloads and download 
the OS X 10.10 SDK, then I think it should work, at least that works on 
10.9 (and became a mandatory step sometime in the past).

I don’t know if the command could be made to use the stuff in the 
Tokens directory.

**Comment by jacob-carlborg** [comment]
I'll download the documentation and see what happens.

**Comment by jacob-carlborg** [comment]
It works now when I've downloaded the documentation. Thanks.
